# action.yml
name: 'CodeCaster Github Action'
description: 'Send repository to create README by CodeCaster'
author: 'not int must be str'
inputs:
  github-token:
    description: 'Put secrets.GITHUB_TOKEN or other tokens to access by CodeCaster'
    required: true
  code-caster-endpoint:
    description: 'endpoint to generate content'
    required: false
    default: 'https://code-caster.nihiyama.net/gen'
  gen-type:
    description: 'Select generation type (deafult: readme)'
    required: false
    default: 'readme'
  target-revision:
    description: 'Set revision to create content by CodeCaster'
    required: false
    default: ${{ github.sha }}
runs:
  using: 'composite'
  steps:
    - name: Install jq
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    - name: Upload source and generate content
      shell: bash
      run: |
        git archive --format=zip --output=source.zip ${{ inputs.target-revision }}
        response=$(curl -X POST -s ${{ inputs.code-caster-endpoint }}/${{ inputs.gen-type }}/ \
          -H "Authorization: ${CODE_CASTER_REPO_TOKEN}" \
          -H 'accept: application/json' \
          -H 'Content-Type: multipart/form-data' \
          -F "source=@source.zip;type=application/zip" \
          | jq '.token')
        echo "CODE_CASTER_CONTENT_TOKEN=${response}" >> $GITHUB_ENV
    - name: Download and git push
      shell: bash
      run: |
        while true; do
          response=$(curl -X POST -s  -w "%{http_code}" -o "code-caster-readme.md" \
            ${{ inputs.code-caster-endpoint }}/${{ inputs.gen-type }}/${CODE_CASTER_CONTENT_TOKEN} \
            -H "Authotization: Bearer ${CODE_CASTER_REPO_TOKEN}" \
          http_status="${response: -3}"
          if [ "$http_status" -eq 200 ]; then
            break
          elif [ "$http_status" -eq 102 ]; then
            echo "Be generating content "
            continue
          else
            echo "Not found content"
            exit 1
          fi
          sleep 3
        cat code-caster-readme.md
